import "@/styles/globals.css";
//
import { headers } from "next/headers";
import { Poppins } from "next/font/google";
import { Slide, ToastContainer } from "react-toastify";

const primaryFont = Poppins({
    subsets: ["latin"],
    weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata = {
    title: "NextJS template",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    const headersList = headers();
    // URI (SSR)
    const header_url = headersList.get("x-url") || "";

    return (
        <html lang="en">
            <body className={primaryFont.className}>
                {children}
                <ToastContainer
                    closeOnClick
                    transition={Slide}
                    hideProgressBar={false}
                />
            </body>
        </html>
    );
}
